user  root;
worker_processes  4;

error_log /var/log/nginx/error.log warn;

events {
	worker_connections  1024;
}

http {
	include       mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
	'$status $body_bytes_sent "$http_referer" '
	'"$http_user_agent" "$http_x_forwarded_for"';

	access_log  /var/log/nginx/access.log  main;

	keepalive_timeout  60;
	keepalive_requests 100000;
	client_max_body_size 1024M;

	server {
		listen       80;
		server_name  localhost;

		root /sdcard/falcon/;

		# 查看目录结构
		location /folderlist {
			alias /sdcard/falcon/;
			autoindex on;
			autoindex_format json;
		}

		# 下载文件
		location /files/download {
			alias /sdcard/falcon/;
			add_header Content-Disposition 'attachment';
		}

		# 在线播放
		location /files/play {
			alias /sdcard/falcon/;
			location ~ \.mp4$ {
				mp4;
				mp4_buffer_size 2m;
				mp4_max_buffer_size 10m;
			}
		}

		# 上传OTA文件
		location ~ ^/files/ota/(.+)$ {
			upload_pass /files/ota_upload_handler;
			upload_store /userdata/ota/tmp;
			upload_store_access user:rw group:rw all:rw;

			include fastcgi_params;

			# 上传失败时清理临时文件
			upload_cleanup 400 403 404 499 500-505;
		}

		location /files/ota_upload_handler {
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/ota_upload_after.sh;
			include fastcgi_params;
		}

		# 获取指定目录下所有文件信息
		location /filelist {
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/get_filelist.sh;
			include fastcgi_params;
		}

		# 获取record_id对应的所有文件信息
		location /relatedfilelist {
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/get_related_filelist.sh;
			include fastcgi_params;
		}

		# 收藏文件
		location ~ ^/files/collect/(.+)$ {
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/collect_file.sh;
			include fastcgi_params;
		}

		# 删除文件
		location ~ ^/files/delete/(.+)$ {
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/delete_file.sh;
			include fastcgi_params;
		}

		# 批量删除文件
		location ~ ^/files/batch-delete {
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/delete_files_json.sh;
			include fastcgi_params;
		}

		# 设置文件别名
		location ~ ^/files/alias/(.+)$ {
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/set_file_alias.sh;
			include fastcgi_params;
		}

		# 获取日志目标文件名
		location /syslog/targetfile {
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/get_syslog_target_file.sh;
			include fastcgi_params;
		}

		#下载日志目标文件
		location /syslog/download/t {
			alias /tmp/;
			add_header Content-Disposition 'attachment';
			#post_action /delete_syslog_target_file;
		}

		location /syslog/download/s {
			alias /userdata/;
			add_header Content-Disposition 'attachment';
			#post_action /delete_syslog_target_file;
		}

		location /delete_syslog_target_file {
			#internal;
			fastcgi_pass unix:/run/fcgiwrap.sock;
			fastcgi_param SCRIPT_FILENAME /oem/usr/scripts/nginx/delete_syslog_target_file.sh;
			include fastcgi_params;
		}

		#产测下载
		location /factory/log/download {
			alias /userdata/;
			add_header Content-Disposition 'attachment';
		}

		location /factory/log/folderlist {
			alias /userdata/;
			autoindex on;
			autoindex_format json;
		}

		# 浏览器测试网页
		location /test {
			alias /sdcard/falcon/;
			index test.html test.html;
		}
	}
}