driver=nl80211
interface=wlan1
ssid=Xbt-F-000000
wpa=3
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
wpa_passphrase=cd20d767bbe
rsn_pairwise=CCMP
ctrl_interface=/var/run/hostapd
eap_server=1
wps_state=2
ap_setup_locked=1
wps_pin_requests=/var/run/hostapd.pin-req
device_name=Wireless AP
manufacturer=Qualcomm
config_methods=label virtual_display virtual_push_button keypad
hw_mode=a
channel=36
ieee80211n=1
ieee80211ac=1
ieee80211ax=1
ht_capab=[HT40-][HT40+][SHORT-GI-20][SHORT-GI-40]
he_oper_chwidth=1
logger_syslog_level=2
logger_syslog=127
