user=root
interface=wlan1
no-dhcp-interface=wlan0
listen-address=192.168.5.1
dhcp-range=192.168.5.2,192.168.5.100,255.255.255.0,12h
dhcp-option=3
dhcp-leasefile=/var/lib/misc/dnsmasq.leases
# 不使用系统默认 resolv.conf 文件中的上游 DNS（因为无外网）
no-resolv
log-dhcp
log-facility=/userdata/logs/dnsmasq.log